AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ROQuestManager
Resources:
  ROQuestManager:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      Role: arn:aws:iam::176973848769:role/lambda_basic_execution
      Timeout: 60
      CodeUri: ./lambda/custom